export const mockdata = {
  "productos": [
    {
      "id": 123456,
      "nombre": "Silla XHD",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "Iniciado",
      "pedido": 19371,
      "cliente": 12345,
      "empresa": "Sillana",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    },
    {
      "id": 442456,
      "nombre": "Silla POD",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "En transito",
      "pedido": 19371,
      "cliente": 12345,
      "empresa": "Sillana",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    },
    {
      "id": 234536,
      "nombre": "Silla DAFS",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "Entregado",
      "pedido": 19371,
      "cliente": 12345,
      "empresa": "Sillana",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    },
    {
      "id": 345646,
      "nombre": "Silla HJSW",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "Entregado",
      "pedido": 19371,
      "cliente": 12345,
      "empresa": "Sillana",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    },
    {
      "id": 927832,
      "nombre": "Mesa Air",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "Entregado",
      "pedido": 29752,
      "cliente": 12345,
      "empresa": "MeSones",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    },
    {
      "id": 635282,
      "nombre": "Iphone 3",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "Iniciado",
      "pedido": 31263,
      "cliente": 12345,
      "empresa": "Apple",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    },
    {
      "id": 197213,
      "nombre": "Boligrafo",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "Iniciado",
      "pedido": 42343,
      "cliente": 12345,
      "empresa": "Bic",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    },
    {
      "id": 888888,
      "nombre": "Fornite",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "Entregado",
      "pedido": 52345,
      "cliente": 12345,
      "empresa": "Videojuegos",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    },
    {
      "id": 888888,
      "nombre": "Fornite",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "Entregado",
      "pedido": 64345,
      "cliente": 33345,
      "empresa": "Videojuegos",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    },
    {
      "id": 273798,
      "nombre": "Estanteria Level3",
      "descripcion": "Lorem ipsum dolor sit amet. Sed cupiditate assumenda vel atque minus ut harum consequatur sit cupiditate dolorem et quidem voluptate eum voluptatem voluptate id reiciendis dolorem.",
      "estado": "Iniciado",
      "pedido": 68283,
      "cliente": 12345,
      "empresa": "Estantinos",
      "transportista": "1111 AAA",
      "res_prod": 2,
      "res_envio": 3,
      "res_esc": ""
    }
  ],
  "total": 6,
  "skip": 0,
  "limit": 6
};